/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangDocsRouteImport } from './routes/$lang/docs'
import { Route as LangDownloadRouteImport } from './routes/$lang/download'
import { Route as LangReleasesRouteImport } from './routes/$lang/releases'
import { Route as LangRoadmapRouteImport } from './routes/$lang/roadmap'
import { Route as LangBlogIndexRouteImport } from './routes/$lang/blog/index'
import { Route as LangBlogSlugRouteImport } from './routes/$lang/blog/$slug'
import { Route as LangDocsIndexRouteImport } from './routes/$lang/docs/index'
import { Route as LangDocsSlugRouteImport } from './routes/$lang/docs/$slug'
import { Route as LangPluginsIndexRouteImport } from './routes/$lang/plugins/index'
import { Route as LangPluginsIdRouteImport } from './routes/$lang/plugins/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangDocsRoute = LangDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => LangRoute,
} as any)
const LangDownloadRoute = LangDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => LangRoute,
} as any)
const LangReleasesRoute = LangReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => LangRoute,
} as any)
const LangRoadmapRoute = LangRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => LangRoute,
} as any)
const LangBlogIndexRoute = LangBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LangRoute,
} as any)
const LangBlogSlugRoute = LangBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangDocsIndexRoute = LangDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangDocsRoute,
} as any)
const LangDocsSlugRoute = LangDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangDocsRoute,
} as any)
const LangPluginsIndexRoute = LangPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => LangRoute,
} as any)
const LangPluginsIdRoute = LangPluginsIdRouteImport.update({
  id: '/plugins/$id',
  path: '/plugins/$id',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/docs': typeof LangDocsRouteWithChildren
  '/$lang/download': typeof LangDownloadRoute
  '/$lang/releases': typeof LangReleasesRoute
  '/$lang/roadmap': typeof LangRoadmapRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/docs/$slug': typeof LangDocsSlugRoute
  '/$lang/plugins/$id': typeof LangPluginsIdRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/docs/': typeof LangDocsIndexRoute
  '/$lang/plugins/': typeof LangPluginsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/download': typeof LangDownloadRoute
  '/$lang/releases': typeof LangReleasesRoute
  '/$lang/roadmap': typeof LangRoadmapRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/docs/$slug': typeof LangDocsSlugRoute
  '/$lang/plugins/$id': typeof LangPluginsIdRoute
  '/$lang/blog': typeof LangBlogIndexRoute
  '/$lang/docs': typeof LangDocsIndexRoute
  '/$lang/plugins': typeof LangPluginsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/docs': typeof LangDocsRouteWithChildren
  '/$lang/download': typeof LangDownloadRoute
  '/$lang/releases': typeof LangReleasesRoute
  '/$lang/roadmap': typeof LangRoadmapRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/docs/$slug': typeof LangDocsSlugRoute
  '/$lang/plugins/$id': typeof LangPluginsIdRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/docs/': typeof LangDocsIndexRoute
  '/$lang/plugins/': typeof LangPluginsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/docs'
    | '/$lang/download'
    | '/$lang/releases'
    | '/$lang/roadmap'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/docs/$slug'
    | '/$lang/plugins/$id'
    | '/$lang/blog/'
    | '/$lang/docs/'
    | '/$lang/plugins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/download'
    | '/$lang/releases'
    | '/$lang/roadmap'
    | '/$lang'
    | '/$lang/blog/$slug'
    | '/$lang/docs/$slug'
    | '/$lang/plugins/$id'
    | '/$lang/blog'
    | '/$lang/docs'
    | '/$lang/plugins'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/docs'
    | '/$lang/download'
    | '/$lang/releases'
    | '/$lang/roadmap'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/docs/$slug'
    | '/$lang/plugins/$id'
    | '/$lang/blog/'
    | '/$lang/docs/'
    | '/$lang/plugins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/docs': {
      id: '/$lang/docs'
      path: '/docs'
      fullPath: '/$lang/docs'
      preLoaderRoute: typeof LangDocsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/download': {
      id: '/$lang/download'
      path: '/download'
      fullPath: '/$lang/download'
      preLoaderRoute: typeof LangDownloadRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/releases': {
      id: '/$lang/releases'
      path: '/releases'
      fullPath: '/$lang/releases'
      preLoaderRoute: typeof LangReleasesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/roadmap': {
      id: '/$lang/roadmap'
      path: '/roadmap'
      fullPath: '/$lang/roadmap'
      preLoaderRoute: typeof LangRoadmapRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/blog/': {
      id: '/$lang/blog/'
      path: '/blog'
      fullPath: '/$lang/blog/'
      preLoaderRoute: typeof LangBlogIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/blog/$slug': {
      id: '/$lang/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$lang/blog/$slug'
      preLoaderRoute: typeof LangBlogSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/docs/': {
      id: '/$lang/docs/'
      path: '/'
      fullPath: '/$lang/docs/'
      preLoaderRoute: typeof LangDocsIndexRouteImport
      parentRoute: typeof LangDocsRoute
    }
    '/$lang/docs/$slug': {
      id: '/$lang/docs/$slug'
      path: '/$slug'
      fullPath: '/$lang/docs/$slug'
      preLoaderRoute: typeof LangDocsSlugRouteImport
      parentRoute: typeof LangDocsRoute
    }
    '/$lang/plugins/': {
      id: '/$lang/plugins/'
      path: '/plugins'
      fullPath: '/$lang/plugins/'
      preLoaderRoute: typeof LangPluginsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/plugins/$id': {
      id: '/$lang/plugins/$id'
      path: '/plugins/$id'
      fullPath: '/$lang/plugins/$id'
      preLoaderRoute: typeof LangPluginsIdRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangDocsRouteChildren {
  LangDocsSlugRoute: typeof LangDocsSlugRoute
  LangDocsIndexRoute: typeof LangDocsIndexRoute
}

const LangDocsRouteChildren: LangDocsRouteChildren = {
  LangDocsSlugRoute: LangDocsSlugRoute,
  LangDocsIndexRoute: LangDocsIndexRoute,
}

const LangDocsRouteWithChildren = LangDocsRoute._addFileChildren(
  LangDocsRouteChildren,
)

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangDocsRoute: typeof LangDocsRouteWithChildren
  LangDownloadRoute: typeof LangDownloadRoute
  LangReleasesRoute: typeof LangReleasesRoute
  LangRoadmapRoute: typeof LangRoadmapRoute
  LangIndexRoute: typeof LangIndexRoute
  LangBlogSlugRoute: typeof LangBlogSlugRoute
  LangPluginsIdRoute: typeof LangPluginsIdRoute
  LangBlogIndexRoute: typeof LangBlogIndexRoute
  LangPluginsIndexRoute: typeof LangPluginsIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangDocsRoute: LangDocsRouteWithChildren,
  LangDownloadRoute: LangDownloadRoute,
  LangReleasesRoute: LangReleasesRoute,
  LangRoadmapRoute: LangRoadmapRoute,
  LangIndexRoute: LangIndexRoute,
  LangBlogSlugRoute: LangBlogSlugRoute,
  LangPluginsIdRoute: LangPluginsIdRoute,
  LangBlogIndexRoute: LangBlogIndexRoute,
  LangPluginsIndexRoute: LangPluginsIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
